### ISSUE TITLE
Fix GET-USERS command

### ISSUE THREAD

**Issue by connorkendrick** [olig1905/listenersClubBot#14]
Currently, when the command GET-USERS is sent to the bot, the bot returns back "Your Command has been processed.", rather than a list of users.

**Comment by matt-garner** [comment]
When returning a reply back to the user we should always try to pass messages back that give appropriate information as to what the result of the command was. As such, I'll design this to return from the parsing methods to pass back a list of the users as the success object to be returned to the parsing method.

**Comment by matt-garner** [comment]
Fixed the handling of this in my new [pull request](https://github.com/olig1905/listenersClubBot/pull/16)
